[package]
name = "rust-iris-classifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Machine Learning
linfa = "0.7.0"
linfa-svm = "0.7.0"
ndarray = "0.15.6"

# Data Handling
polars = { version = "0.36.2", features = ["lazy", "reqwest"] }

# Plotting
plotters = "0.3.5"

# Serialization
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
